server:
  port: 9080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/fox_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  redis:
    host: 192.168.253.130
    port: 6379
    timeout: 10000
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: false
user:
  dir: E:\2005\@Gitee\fox_shop_perent
  jwtset:
    signature: "jiaoqiyang"
    exptime: 36000000
    alg: "HS256"
    type: "JWT"


